/* Console modules included in the demo (route under /procure). */
export const PROCURE_PAGES = [
  { slug: 'cockpit', path: '/procure/cockpit', name: 'Dashboard' },
  { slug: 'freight-bills', path: '/procure/freight-bills', name: 'Freight Bills' },
  { slug: 'dispatch-requests', path: '/procure/dispatch-requests', name: 'Dispatch Requests' },
  { slug: 'order-pipeline', path: '/procure/order-pipeline', name: 'Order Pipeline' },
  { slug: 'booking-board', path: '/procure/booking-board', name: 'Booking Board' },
  { slug: 'inbound-orders', path: '/procure/inbound-orders', name: 'Inbound Orders' },
  { slug: 'receiving-monitor', path: '/procure/receiving-monitor', name: 'Receiving Monitor' },
  { slug: 'inbound-calendar', path: '/procure/inbound-calendar', name: 'Inbound Shipment' },
  { slug: 'container-ledger', path: '/procure/container-ledger', name: 'Container Ledger' },
  { slug: 'margin-console', path: '/procure/margin-console', name: 'Channel Margin Console' },
  { slug: 'marketplace-sheet', path: '/procure/marketplace-sheet', name: 'Marketplace Sheet' },
  { slug: 'storefront-sheet', path: '/procure/storefront-sheet', name: 'Storefront Sheet' },
  { slug: 'long-tail-channels', path: '/procure/long-tail-channels', name: 'Long-tail Channels' },
  { slug: 'flagged-skus', path: '/procure/flagged-skus', name: 'Flagged SKUs' },
  { slug: 'ad-spend', path: '/procure/ad-spend', name: 'Ad Spend vs Revenue' },
  { slug: 'availability-score', path: '/procure/availability-score', name: 'Availability Score' },
  { slug: 'demand-planner', path: '/procure/demand-planner', name: 'Demand Planner' },
  { slug: 'storefront-stock', path: '/procure/storefront-stock', name: 'Storefront Stock' },
  { slug: 'sales-by-month', path: '/procure/sales-by-month', name: 'Sales by Month' },
  { slug: 'availability-by-month', path: '/procure/availability-by-month', name: 'Availability by Month' },
  { slug: 'reorder-decisions', path: '/procure/reorder-decisions', name: 'Reorder Decisions' },
] as const
