export const profile = {
  name: 'Joe Marie Casela',
  initials: 'JM',
  title: 'Workflow & AI Automation Specialist',
  tagline: 'n8n • Make • GoHighLevel • Zapier • Apps Script',
  location: 'Lucena City, Philippines (Remote)',
  email: 'tech.joemarie@gmail.com',
  phone: '+63 927 856 6186',
  phoneHref: 'tel:+639278566186',
  /* Google Calendar appointment schedule (Calendar → Create → Appointment schedule → Share → copy the booking-page link).
     Leave empty to fall back to a mailto link on the Book button. */
  calendar: 'https://calendly.com/tech-joemarie/30min?hide_gdpr_banner=1&primary_color=ee5a2b&text_color=1a1a1a&background_color=f6f5f2',
  linkedin: 'https://www.linkedin.com/in/techjoemarie',
  upwork: 'https://www.upwork.com/freelancers/joemariecasela',
  onlinejobs: 'https://www.onlinejobs.ph/jobseekers/info/3334524',
  whatsapp: 'https://wa.me/639278566186?text=Hi%20Joe%2C%20I%20have%20a%20bottleneck%20I%27d%20like%20to%20automate',
  viber: 'viber://chat?number=%2B639278566186',
  site: 'https://workwithjm.onrender.com/',
  photo: '/joe.jpg',
  availability: 'Accepting two engagements this quarter',
  specialties: ['Enterprise automation', 'AI agents', 'Internal platforms', 'Operations intelligence'],
}

export type Tool = { name: string; icon?: string; logo?: string; color: string; initials?: string }
/* `icon` = Simple Icons slug (cdn.simpleicons.org); `logo` = self-hosted brand mark in public/logos; a concept (not a brand) gets a monogram badge. */
export const tools: Tool[] = [
  { name: 'n8n', icon: 'n8n', color: 'EA4B71' }, { name: 'Make.com', icon: 'make', color: '6D00CC' }, { name: 'Zapier', icon: 'zapier', color: 'FF4F00' },
  { name: 'GoHighLevel', logo: '/logos/gohighlevel.png', color: '' }, { name: 'Google Gemini', icon: 'googlegemini', color: '8E75B2' }, { name: 'OpenAI', logo: '/logos/openai.png', color: '' },
  { name: 'VAPI Voice AI', logo: '/logos/vapi.png', color: '' }, { name: 'RAG pipelines', color: 'EE5A2B', initials: 'RAG' },
  { name: 'React.js', icon: 'react', color: '61DAFB' }, { name: 'Next.js', icon: 'nextdotjs', color: '000000' }, { name: 'Node.js', icon: 'nodedotjs', color: '5FA04E' }, { name: 'Express', icon: 'express', color: '000000' },
  { name: 'Supabase', icon: 'supabase', color: '3FCF8E' }, { name: 'Postgres', icon: 'postgresql', color: '4169E1' }, { name: 'Shopify API', icon: 'shopify', color: '7AB55C' }, { name: 'Maya Checkout', logo: '/logos/maya.png', color: '' },
  { name: 'Google Apps Script', icon: 'googleappsscript', color: '4285F4' }, { name: 'Airtable', icon: 'airtable', color: '18BFFF' }, { name: 'Asana', icon: 'asana', color: 'F06A6A' }, { name: 'Monday.com', logo: '/logos/monday.png', color: '' },
  { name: 'ClickUp', icon: 'clickup', color: '7B68EE' }, { name: 'Salesforce', logo: '/logos/salesforce.png', color: '' }, { name: 'Docker', icon: 'docker', color: '2496ED' }, { name: 'Vercel', icon: 'vercel', color: '000000' },
  { name: 'Render', icon: 'render', color: '000000' }, { name: 'Netlify', icon: 'netlify', color: '00C7B7' }, { name: 'Postman', icon: 'postman', color: 'FF6C37' }, { name: 'Figma', icon: 'figma', color: 'F24E1E' },
]

export const services = [
  {
    icon: 'app',
    title: 'Order-to-Delivery Operations Platforms',
    blurb: 'One internal system that runs the whole order lifecycle: orders from the showroom, website and Messenger, payments, production workshops, quality control, warehouse, delivery teams, installation and warranty.',
    bullets: ['One login per role: sales, production, warehouse, drivers, finance, HR, management', 'Workshop jobs with material stock, QC pay-per-piece and a location-level warehouse ledger', 'Driver tablets with live GPS routes, pickup tasks, on-site rework and returns'],
    detail: 'I built this for Pan Furniture on Next.js and Supabase, and it is the live demo on this page. It issues BIR-compliant service invoices, takes payments through Maya Checkout, runs three production workshops with their own material stock, receives goods into 1,200 barcode-scanned storage locations, plans routes for four delivery teams with on-site rework, and keeps installation, warranty, HR and payroll records in the same database. Every screen updates in realtime because the app reads the same tables the workflows write to.',
  },
  {
    icon: 'workflow',
    title: 'Purchasing & Inventory Intelligence',
    blurb: 'A purchasing console for a catalogue of thousands of SKUs: a forecast grid, a reorder planner ranked by urgency, purchase-order, invoice and shipping-request trackers, and a container booking board.',
    bullets: ['Forecast report with 100+ columns per SKU and a reorder planner that says what to order and when', 'PO, invoice and shipping-request trackers with inline editing, comments, @mentions and attachments', 'Weekly reorder and storefront-inventory emails sent to each vendor owner automatically'],
    detail: 'I designed and shipped this for an e-commerce client on React and Supabase. Nightly syncs from their ERP, storefront and marketplaces feed a forecast engine that computes sales velocity, monthly projections, months of supply and recommended order quantities for every SKU. Buyers work in spreadsheet-style grids with grouping, filtering, saved views, CSV import and server-side XLSX export. Access is controlled per role and per vendor with row-level security and MFA sign-in, and a booking board shows which containers to book each week. The 21 purchasing-console demos above follow the same design, rebuilt on invented data.',
  },
  {
    icon: 'crm',
    title: 'Workflow Automation (n8n · Make · Zapier)',
    blurb: 'Automations that run on your own accounts and are triggered by real events in your systems: an approved order, a QC pass, a cargo-ready date, a status change on an invoice.',
    bullets: ['Eight production webhooks for Pan Furniture: receipts, delivery confirmations, made-to-order intake, push alerts', 'Scheduled vendor reports and approval-chain emails for the purchasing console, all through n8n', 'A written SOP and a walkthrough video for every workflow, so your team can maintain it'],
    detail: 'At Pan Furniture, n8n handles order receipts, delivery confirmations, made-to-order intake from chat and push notifications to staff phones. For the e-commerce client, n8n sends the weekly reorder-planner and storefront-inventory reports per vendor, fires the approval and payment emails when an invoice or shipping request changes status, notifies people mentioned in comments, and refreshes the in-stock figures on a schedule. Every workflow writes its result back to the same tables, retries quietly on failure and escalates to a named person when a step needs a human.',
  },
  {
    icon: 'bot',
    title: 'AI Agents & Chatbots',
    blurb: 'Gemini and OpenAI agents that answer customers on Messenger, web chat or voice, using your own product data and a response library your team maintains, with a hand-off to a real person when needed.',
    bullets: ['Facebook Messenger agent answering price, stock, delivery and warranty questions around the clock', 'Made-to-order requests captured from the conversation and created directly in the operations system', 'Keywords, replies, priorities and fallback managed by the sales team in the admin, not in code'],
    detail: 'The Pan Furniture Messenger agent reads live product and stock data, answers from a script library the sales team edits themselves in the admin console, creates made-to-order requests and quotations from the chat, and hands sensitive or unresolved conversations to a named staff member with the full thread. The same pattern extends to retrieval over Supabase Vector or document folders for teams with larger knowledge bases.',
  },
  {
    icon: 'data',
    title: 'Integrations & Data Pipelines',
    blurb: 'Connecting the storefront, marketplaces, ERP, payment gateways and messaging platforms to one database, using each platform\'s own API, with webhooks and nightly reconciliation.',
    bullets: ['Shopify, marketplace and ERP syncs into one Supabase database for the purchasing console', 'Maya Checkout, Facebook Graph and push-notification integrations for Pan Furniture', 'Idempotent writes and audit logs, so a retried webhook never double-posts a payment or an order'],
    detail: 'For the e-commerce client, orders, inventory, product details and ad-platform data are pulled from Shopify, the marketplaces, the ERP and the ad accounts into Postgres tables the console reads directly, with a nightly reconciliation of order and revenue totals. For Pan Furniture, payments, Facebook page events and mobile push notifications are wired into the operations platform the same way. No spreadsheets sit between the source and the screen.',
  },
  {
    icon: 'chart',
    title: 'Forecasting, Analytics & Reporting',
    blurb: 'Dashboards and forecasts computed from the operating tables themselves: demand projections, reorder points, in-stock rate, blended advertising ROAS, contribution margin per SKU and per channel, and sales command centres.',
    bullets: ['Monthly projection and supply plan per SKU, with a recommended order quantity and order date', 'Sales analytics with CM1 / CM2 / CM3 per channel, in-stock rate by month and a blended ROAS view', 'Executive sales dashboard, finance summary and performance rankings for a retail operation'],
    detail: 'The forecast engine behind the purchasing console projects each SKU month by month, subtracts incoming stock and lead time, and turns the result into an order date and quantity. The analytics pages compute contribution margins per channel from landed cost, fees and marketing spend, track in-stock rate against a target, and blend ad spend across platforms against storefront revenue. For Pan Furniture, the Sales Command Center and finance views read the live order and payment tables, so any number on screen can be traced to the order behind it.',
  },
]

export const steps = [
  {
    title: 'Discovery & process audit',
    body: 'We map your operational workflows end-to-end, quantify where time and margin are lost, and prioritise the automation candidates by business impact and risk.',
    deliver: 'A documented process map, a prioritised automation roadmap and a business case',
  },
  {
    title: 'Solution architecture & approval',
    body: 'Architecture, data flows, integrations, access controls and failure handling are specified and signed off before implementation begins, with a fixed scope and price.',
    deliver: 'An approved technical design, delivery plan and fixed-scope statement of work',
  },
  {
    title: 'Implementation, validation & handover',
    body: 'Built to specification, tested against production edge cases, deployed on your own infrastructure with audit trails, retry logic and named escalation owners.',
    deliver: 'The production system, operational documentation, training and a defined support window',
  },
]

export type Demo = {
  slug: string
  name: string
  kicker: string
  blurb: string
  tags: string[]
  outcome: string
  client: string
  /** route the live frame loads; defaults to /demo/<slug> */
  route?: string
  /** optional second column in the frame's info panel */
  problem?: string
  solution?: string
  /** static thumbnail for the card; falls back to the drawn poster */
  image?: string
  /** internal case-study page */
  caseStudy?: string
  /** console modules: the filter group they belong to in the showcase */
  category?: string
  /** console modules: which product they belong to (Pan cards have none) */
  product?: 'console'
}

export const demos: Demo[] = [
  {
    slug: 'procure-dashboard',
    product: 'console', category: 'Dashboards & analytics',
    name: 'Replenishment Cockpit',
    kicker: 'Northwind — buyer overview',
    blurb: 'Landing page of the buying team: urgency counters (urgent, within 20 / 45 / 75 days), new-orders and shipped revenue for the last 31 days, and four Demand Planner panels that list exactly which SKUs to order now, next month and the month after — with the reason and stock-out date on every row.',
    tags: ['React', 'Recharts', 'Supabase', 'Nightly refresh'],
    outcome: 'Order now / 30 / 60 / 90-day queues',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/cockpit',
    image: '/procure/cockpit.png',
  },
  {
    slug: 'procure-invoice-tracker',
    product: 'console', category: 'Purchasing',
    name: 'Freight Bills',
    kicker: 'Northwind — freight billing',
    blurb: 'Every ocean shipment as a freight invoice: HBL/MBL, DDP, forwarder, arrival notice and freight-invoice checks, telex release, vendor, origin, carrier, ATD/ATA and delay, vessel, 40HC count, multi-pill invoice status, payment due, rate and amount due. Group, filter, sort, hide fields, inline edits, comments with @mentions.',
    tags: ['React', 'Supabase', 'Airtable-style grid', 'Inline edit'],
    outcome: 'Freight invoices reconciled per container',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/freight-bills',
    image: '/procure/freight-bills.png',
  },
  {
    slug: 'procure-shipping-requests',
    product: 'console', category: 'Shipping',
    name: 'Dispatch Requests',
    kicker: 'Northwind — factory dispatch',
    blurb: 'Factory-side shipping requests from intake to booking: calculated REF, progress pills (Requested, In Review, Instructions Sent, Fully Approved…), QC check, inspection and cargo-ready dates, CBM, POL, packing list previews, factory notes, PO numbers and approvals — with a request log, comments and file attachments.',
    tags: ['React', 'Supabase', 'Storage uploads', 'n8n notifications'],
    outcome: 'Cargo-ready → booked, one row',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/dispatch-requests',
    image: '/procure/dispatch-requests.png',
  },
  {
    slug: 'procure-po-tracker',
    product: 'console', category: 'Purchasing',
    name: 'Order Pipeline',
    kicker: 'Northwind — PI to shipment',
    blurb: 'Purchase orders with vendor, PO type, status, team status (Awaiting Quote, Deposit Requested, Confirmed…), priority, target completion, factory, origin, product count, dates, ship/receive state, payment status and approvals, deposit maths and the PO / PI document slots — plus notes, reminders and comments per PO.',
    tags: ['React', 'Supabase', 'Airtable-style grid', 'Documents'],
    outcome: 'PI → deposit → shipment, tracked',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/order-pipeline',
    image: '/procure/order-pipeline.png',
  },
  {
    slug: 'procure-booking-dashboard',
    product: 'console', category: 'Purchasing',
    name: 'Booking Board',
    kicker: 'Northwind — weekly bookings',
    blurb: 'The weekly booking board: ready-for-booking vs booked, overdue past cargo-ready date, containers in scope, needs-booking by factory, booked by carrier, a 12-week ready-vs-booked tally and the unbooked backlog by urgency — computed live from the shipping requests.',
    tags: ['React', 'Supabase realtime', 'SVG charts'],
    outcome: 'Book the red ones first',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/booking-board',
    image: '/procure/booking-board.png',
  },
  {
    slug: 'procure-purchase-orders',
    product: 'console', category: 'Purchasing',
    name: 'Inbound Orders',
    kicker: 'Northwind — inbound orders',
    blurb: 'Every open and received purchase-order line by vendor and PO number: unit cost, requested and expected dates, quantities ordered vs received and a delivery status (Pending, Partial, Received, Overdue). Grouped by CRD week, filterable per column, with import, export and row edits.',
    tags: ['React', 'Supabase', 'CSV import', 'Server export'],
    outcome: 'What is arriving, and when',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/inbound-orders',
    image: '/procure/purchase-orders.png',
  },
  {
    slug: 'procure-inventory-arrivals',
    product: 'console', category: 'Inventory & planning',
    name: 'Receiving Monitor',
    kicker: 'Northwind — receiving',
    blurb: 'Latest receipts first: PO number and date, warehouse, vendor, product, price, received date, quantity received and the on-hand count before the receipt. The log the warehouse team checks against the containers.',
    tags: ['React', 'Supabase', 'Column filters', 'Import / export'],
    outcome: 'Receipts reconciled the same day',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/receiving-monitor',
    image: '/procure/receiving-monitor.png',
  },
  {
    slug: 'procure-incoming-shipment',
    product: 'console', category: 'Inventory & planning',
    name: 'Inbound Shipment',
    kicker: 'Northwind — inbound by month',
    blurb: 'Open PO quantities pivoted into the next twelve months per product, with the PO numbers behind each cell, row totals and the peak month. The planner sees which SKUs are covered and which need another order.',
    tags: ['React', 'Supabase view', 'TanStack Query'],
    outcome: '12-month inbound pivot per SKU',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/inbound-calendar',
    image: '/procure/inbound-calendar.png',
  },
  {
    slug: 'procure-containers',
    product: 'console', category: 'Shipping',
    name: 'Container Ledger',
    kicker: 'Northwind — door to door',
    blurb: 'Container by container: PO, container name, shipped-on, ETA at port, estimated arrival, received date, invoice, notes, product lines, receiving warehouse, quantities and vessel. Per-row actions, CSV import and export.',
    tags: ['React', 'Supabase', 'CSV import', 'Server export'],
    outcome: 'Containers tracked door to door',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/container-ledger',
    image: '/procure/containers.png',
  },
  {
    slug: 'procure-sales-analytics',
    product: 'console', category: 'Dashboards & analytics',
    name: 'Channel Margin Console',
    kicker: 'Northwind — CM1 / CM2 / CM3',
    blurb: 'Nine live period cards (today, yesterday, MTD, forecast, last month, four closed months) with CM1/CM2/CM3 contribution margins, channel pills for Website, Marketplace A, Dropship Partner, Marketplace B, Amazon and Marketplace C, and a best-sellers ledger with landed COGS, shipping, fees, returns and OPEX per SKU.',
    tags: ['React', 'Supabase', 'the ERP', 'Contribution margin'],
    outcome: 'CM3 per SKU per channel, daily',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/margin-console',
    image: '/procure/sales-analytics.png',
  },
  {
    slug: 'procure-amazon-dashboard',
    product: 'console', category: 'Dashboards & analytics',
    name: 'Marketplace Sheet',
    kicker: 'Northwind — marketplace channel',
    blurb: 'Per-SKU sheet for the Amazon channel: five months of in-stock %, five months of units, a forward monthly projection, a six-month supply plan, incoming shipments by month and the 30/60/90-day incoming breakdown — with images, product info, group/filter/sort and XLSX export.',
    tags: ['React', 'TanStack Query', 'Supabase', 'XLSX export'],
    outcome: 'Instock % + projection per SKU',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/marketplace-sheet',
    image: '/procure/marketplace-sheet.png',
  },
  {
    slug: 'procure-website-dashboard',
    product: 'console', category: 'Dashboards & analytics',
    name: 'Storefront Sheet',
    kicker: 'Northwind — storefront channel',
    blurb: 'The same sheet for the brand storefront: in-stock history, monthly units, projection, supply plan and incoming — so the web team sees exactly what the buyers see, on the storefront\'s own numbers.',
    tags: ['React', 'TanStack Query', 'Supabase', 'XLSX export'],
    outcome: 'Storefront demand vs supply',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/storefront-sheet',
    image: '/procure/storefront-sheet.png',
  },
  {
    slug: 'procure-other-channel-dashboard',
    product: 'console', category: 'Dashboards & analytics',
    name: 'Long-tail Channels',
    kicker: 'Northwind — smaller channels',
    blurb: 'Marketplaces and dropship partners rolled into one sheet: in-stock %, units, projection and supply plan per SKU for everything that is not Amazon or the storefront.',
    tags: ['React', 'TanStack Query', 'Supabase', 'XLSX export'],
    outcome: 'Long-tail channels on one grid',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/long-tail-channels',
    image: '/procure/long-tail-channels.png',
  },
  {
    slug: 'procure-needs-attention',
    product: 'console', category: 'Dashboards & analytics',
    name: 'Flagged SKUs',
    kicker: 'Northwind — stagnant and unlisted',
    blurb: 'Only the SKUs that need a decision: stock on hand but no recent sales in any channel, or active in purchasing but missing a storefront listing. Amazon, storefront and other-channel sales side by side with the alert reason and one-click export.',
    tags: ['React', 'TanStack Query', 'Supabase'],
    outcome: 'Stagnant + unlisted SKUs, one list',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/flagged-skus',
    image: '/procure/flagged-skus.png',
  },
  {
    slug: 'procure-ads-analytics',
    product: 'console', category: 'Dashboards & analytics',
    name: 'Ad Spend vs Revenue',
    kicker: 'Northwind — blended ROAS',
    blurb: 'Meta, Google and TikTok spend against Shopify revenue: blended ROAS and CPA tiles, a 30/60/90-day engagement chart, channel performance (spend, impressions, clicks, CTR, CPC, conversions) and the recent Shopify orders the ads produced.',
    tags: ['React', 'Recharts', 'Meta Ads API', 'Shopify'],
    outcome: 'Blended ROAS on one screen',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/ad-spend',
    image: '/procure/ad-spend.png',
  },
  {
    slug: 'procure-instock-rate',
    product: 'console', category: 'Inventory & planning',
    name: 'Availability Score',
    kicker: 'Northwind — Availability Score',
    blurb: 'Where the catalogue sits against the in-stock target: established vs new SKUs, month-by-month cards with deltas, a year-to-date trend, and the SKUs that have never arrived — the report the buying team reviews weekly.',
    tags: ['React', 'Recharts', 'Supabase', 'Nightly refresh'],
    outcome: 'every SKU scored nightly',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/availability-score',
    image: '/procure/instock-rate.png',
  },
  {
    slug: 'procure-forecast-report',
    product: 'console', category: 'Inventory & planning',
    name: 'Demand Planner',
    kicker: 'Northwind — reorder engine',
    blurb: 'The 111-column purchasing grid: in-stock %, monthly sales, projections, revenue and lost revenue, inventory buckets, incoming shipments, supply plan, PO details and the 90-day Reorder Decisions — with column filters, hide/freeze, inline edits, XLSX/CSV export and scheduled factory emails.',
    tags: ['React', 'TanStack Virtual', 'Supabase', 'n8n email'],
    outcome: 'Reorder points computed nightly',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/demand-planner',
    image: '/procure/forecast-report.png',
    problem: 'hundreds of SKUs across several vendors were forecast in a spreadsheet that took an analyst most of Monday to refresh, and buyers only saw it as an emailed PDF.',
    solution: 'Nightly jobs sync the ERP, Shopify and Amazon into Supabase; the planner recomputes projections, supply months and reorder quantities per SKU, and the same grid drives XLSX exports and scheduled per-factory emails through n8n.',
  },
  {
    slug: 'procure-shopify-inventory-page',
    product: 'console', category: 'Inventory & planning',
    name: 'Storefront Stock',
    kicker: 'Northwind — storefront stock',
    blurb: 'Every storefront SKU with on-hand, on-the-water, on-order and PO-in-progress units, plus open-order arrivals bucketed at 30 / 60 / 90 / 120 days. Per-column filters, variant editing (price, barcode, package, weight), and the scheduled email report the merchandising team receives.',
    tags: ['React', 'Shopify', 'Supabase', 'Email schedule'],
    outcome: 'storefront stock on one monitor',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/storefront-stock',
    image: '/procure/shopify-inventory-page.png',
  },
  {
    slug: 'procure-yearly-sales',
    product: 'console', category: 'Dashboards & analytics',
    name: 'Sales by Month',
    kicker: 'Northwind — three years, by month',
    blurb: 'Units or revenue per product per month for any year since 2020, with totals and peak month, Has-Sales filter, search, sorting and XLSX export — the table the buyers use to sanity-check the forecast.',
    tags: ['React', 'Supabase', 'TanStack Query', 'XLSX export'],
    outcome: '3 years of monthly sales, instant',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/sales-by-month',
    image: '/procure/sales-by-month.png',
  },
  {
    slug: 'procure-instock-percentage',
    product: 'console', category: 'Inventory & planning',
    name: 'Availability by Month',
    kicker: 'Northwind — stock-outs by month',
    blurb: 'Monthly in-stock percentage per product for the selected year, average and peak month, Has-Data filter and export — the raw table behind the Availability Score.',
    tags: ['React', 'Supabase', 'Nightly refresh'],
    outcome: 'Stock-out months visible per SKU',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/availability-by-month',
    image: '/procure/availability-by-month.png',
  },
  {
    slug: 'procure-idp',
    product: 'console', category: 'Inventory & planning',
    name: 'Reorder Decisions',
    kicker: 'Northwind — reorder engine',
    blurb: 'The 90-day reorder engine on top of the forecast: urgency buckets (urgent, within 20 / 45 / 75 days), projection vs supply plan per month, deficit and revenue at risk, safety stock, recommended order quantity, lead time, order date and supply month — with per-factory email scheduling and send.',
    tags: ['React', 'Supabase', 'n8n email', 'XLSX'],
    outcome: '90-day deficit → order qty per SKU',
    client: 'Northwind Motor Parts · fictional demo brand',
    route: '/procure/reorder-decisions',
    image: '/procure/decision-planner.png',
  },
  {
    slug: 'pan',
    name: 'Pan IMS',
    kicker: 'Pan Furniture Operations Platform',
    blurb: 'The production system running a real furniture business: showroom and website orders, BIR receipts, Maya payments, three workshops, warehouse cubics, QC, four delivery teams with live GPS, installation, warranty, HR and payroll. Fourteen roles, one database — sign in with any demo role.',
    tags: ['Next.js 16', 'Supabase', 'Maya', 'n8n', 'Android + Desktop'],
    outcome: '95 screens · 14 roles · in production',
    client: 'Pan Furniture · Lucena City',
    route: '/pan?entry=/dashboard',
    image: '/pan/app-dashboard.png',
    caseStudy: '/work/pan-furniture',
    problem: 'Orders lived in Messenger threads and notebooks. Nobody could say which sofa was in which cubic, which workshop was overloaded, or whether Team B had collected the balance — and the owner found out when a customer called.',
    solution: 'One app with a role per seat: sales writes the order, operations approves and dispatches to a workshop, QC declares pay per piece, warehouse scans stock into cubics, drivers run routes on tablets, HR runs payroll from the same attendance. 237 migrations, realtime everywhere.',
  },
  {
    slug: 'pan-tablet',
    name: 'Pan IMS on tablet',
    kicker: 'the same platform on a 10-inch tablet',
    blurb: 'Every screen of the operations platform on the Android tablets the team carries: the same roles, pages and data as the desktop demo, laid out for a tablet with the drawer navigation and full-width tables. Drivers run pickups, reworks, the live GPS route and installation sign-offs; the production area runs jobs, materials, QC and stock requests; managers approve, schedule and check the numbers from the floor.',
    tags: ['Android (Capacitor)', 'Next.js 16', 'Supabase', 'Live GPS', 'Realtime'],
    outcome: 'Tablet layout · all roles',
    client: 'Pan Furniture · Lucena City',
    route: '/pan?device=tablet&role=delivery_team_a&entry=/delivery/routes/team-a',
    image: '/pan/app-tablet.png',
    caseStudy: '/work/pan-furniture',
    problem: 'Field and floor staff were reporting by phone call and photo threads: which items were collected, which stop was done, which job passed QC, which order was approved. Office staff re-typed everything, and the numbers were always a day behind.',
    solution: 'One Android build of the same app, signed in per tablet. Each role sees its own pages: the driver advances stops with proof photos and COD, the workshop declares finished pieces for QC, the manager approves and dispatches from the floor. Every tap writes to the same database the office reads, so the desktop dashboard moves in realtime.',
  },
  {
    slug: 'store',
    name: 'Pan Furniture Storefront',
    kicker: 'the customer-facing store, wired to the same platform',
    blurb: 'The shop customers actually buy from: home page with category rails, ready-to-ship stock, promo beds and a made-to-order section; collections with filters; product pages with fabric swatches, bed sizes and add-ons; quote requests for custom builds; cart and checkout with a map pin for delivery and a 30% downpayment by QR Ph or card; an order-tracker pop-up; Messenger, WhatsApp and Viber contact rail. In production the catalog, banners and reviews are edited inside the IMS and pushed to the site live; orders land in the same database the warehouse works from.',
    tags: ['Next.js 14', 'Tailwind', 'Maya', 'Messenger', 'Supabase'],
    outcome: 'Sample catalog · checkout, quotes & tracking simulated',
    client: 'Pan Furniture · Lucena City',
    route: '/store?entry=/',
    image: '/store/home.png',
    caseStudy: '/work/pan-furniture',
    problem: 'The old site was a brochure: customers still had to message a person to ask prices, sizes and delivery fees, and every order was re-typed into the operations app.',
    solution: 'A storefront on the same database as the IMS. Products, swatches, banners and reviews are edited in the IMS admin and appear on the site without a redeploy; checkout creates the order and its downpayment link, and the tracker reads the order\'s real production stages.',
  },
  {
    slug: 'store-mobile',
    name: 'Pan Furniture Storefront on mobile',
    kicker: 'the same store at phone width',
    blurb: 'The storefront as most customers see it: on a phone. Swipeable category and product rails, the drawer menu, sticky add-to-cart, the contact rail and the track pop-up, all at a real 390-pixel width inside a phone frame.',
    tags: ['Next.js 14', 'Tailwind', 'Responsive', 'Messenger'],
    outcome: 'Mobile layout · same catalog',
    client: 'Pan Furniture · Lucena City',
    route: '/store?device=phone&entry=/',
    image: '/store/app-mobile.png',
    caseStudy: '/work/pan-furniture',
  },
]

export const cases = [
  {
    title: 'Messenger Sales Agent',
    tools: ['n8n', 'Facebook Graph API', 'Supabase'],
    blurb: 'Answers page messages from a script library the sales team edits in the IMS.',
    problem: 'Price, stock and delivery questions arrived all day and piled up on two staff.',
    solution: 'n8n debounces bursts into one reply, matches scored keywords, and pauses for two hours whenever a human replies.',
    metric: '2 h', metricLabel: 'hand-off pause after a human reply',
  },
  {
    title: 'AI Product Photography',
    tools: ['n8n', 'Kie.ai', 'Nano Banana'],
    blurb: 'One phone photo of a bed plus a wood swatch becomes a full studio angle set.',
    problem: 'Every new bed model needed a studio session, and the slat wood never matched the swatch.',
    solution: 'Seven locked prompts run on an image-edit model, poll until done, and return a gallery with a ZIP.',
    metric: '9', metricLabel: 'catalogue shots per bed, in minutes',
  },
  {
    title: 'Transactional Email Suite',
    tools: ['n8n', 'Gmail', 'PDF', 'Maya QR Ph'],
    blurb: 'Eight event-driven emails from for-payment QR to warranty certificate.',
    problem: 'Receipts were attached by hand, sent from personal accounts, sometimes twice.',
    solution: 'The platform renders each PDF and posts it to n8n. One sender module logs every send and blocks duplicates.',
    metric: '8', metricLabel: 'email workflows, zero manual sends',
  },
  {
    title: 'Delivery Confirmation Loop',
    tools: ['n8n', 'Schedule Trigger', 'Next.js API'],
    blurb: 'One-tap delivery confirmations, chased automatically every morning.',
    problem: 'Dates agreed by phone were forgotten; unconfirmed customers surfaced when the truck was loading.',
    solution: 'A 6 AM run sends follow-ups (capped at three, then a call flag) and two-day reminders with Confirm and Reschedule.',
    metric: '06:00', metricLabel: 'daily sweep, capped at 3 follow-ups',
  },
  {
    title: 'Sign-in Verification Codes',
    tools: ['n8n', 'Gmail', 'Supabase'],
    blurb: 'A second factor for staff sign-in using the company Gmail as transport.',
    problem: 'Fourteen roles needed more than a password, with no SMS gateway budget.',
    solution: 'The app issues a 6-digit code with a 5-minute expiry; n8n emails it. Rate limits cap sends and attempts.',
    metric: '5 min', metricLabel: 'code validity, 5 attempts per 10 min',
  },
  {
    title: 'Purchasing Console Reporting',
    tools: ['n8n', 'Supabase', 'Email'],
    blurb: 'Weekly vendor reports, approval emails and nightly stock refresh for a purchasing console.',
    problem: 'Buyers exported spreadsheets by hand and approvals lived in chat threads.',
    solution: 'n8n reads the console tables directly: scheduled per-vendor reports, status-triggered approvals, mention alerts, nightly syncs.',
    metric: 'Weekly', metricLabel: 'per-vendor reports for an e-commerce importer',
  },
]

export const stats = [
  { value: '2', suffix: '', label: 'production platforms in daily use: an operations system and a purchasing console', kicker: 'Platforms', link: '#work', cta: 'Open the demos' },
  { value: '95', suffix: '+', label: 'screens across 14 roles in a single order-to-delivery platform', kicker: 'Operations platform', link: '#work', cta: 'See the platform' },
  { value: '90', suffix: '%', label: 'of customer enquiries resolved by an AI agent, response time cut from hours to seconds', kicker: 'AI agent', link: '#services', cta: 'How it works' },
  { value: '22', suffix: '', label: 'production-grade applications available to evaluate on this page', kicker: 'Interactive demos', link: '#work', cta: 'Evaluate hands-on' },
]

export const experience = [
  {
    company: 'E-commerce importer',
    where: 'United States · Remote',
    when: 'Jan 2026 – Present',
    role: 'Application Developer & Software Engineer',
    about: 'Direct-to-consumer importer selling through its own storefront and online marketplaces.',
    bullets: [
      'Architected and shipped a multi-module purchasing and inventory platform with role-based access.',
      'Built a bi-directional Shopify ↔ Supabase sync powering automated PO generation, supplier lead-time tracking and reorder alerts.',
      'Delivered a demand-forecasting engine, PO approval workflow, receiving, returns management and a reporting suite (forecast, yearly sales, ads analytics, in-stock %, invoice tracking, activity log).',
      'Integrate payment gateways, shipping providers and CRM tools; conduct code reviews and maintain CI/CD and technical documentation.',
    ],
    stack: ['React', 'Node.js', 'Supabase', 'Shopify API', 'REST', 'Vercel'],
  },
  {
    company: 'Pan Furniture',
    where: 'Manila, Philippines',
    when: '2026 – Present',
    role: 'Systems Architect & Automation Lead',
    about: 'Purificacion and Noriega Furniture Shop Co. — a made-to-order furniture manufacturer and retailer with showroom, website and Facebook channels.',
    bullets: [
      'Built the internal operations platform on Next.js 16 and Supabase covering the full order lifecycle: online and in-store orders, BIR service invoicing, Maya payments, workshop jobs, materials inventory, QC, delivery and installation, HR and payroll.',
      'Engineered live delivery tracking for four delivery teams with route planning, pickup tasks, on-site rework and returns/RMA flows.',
      'Wired eight n8n webhooks for email, Messenger and made-to-order request intake, plus a Facebook AI agent for inbound inquiries.',
      'Designed the inventory ledger engine with atomic stock adjustments, barcode scanning and audit trail across three workshops.',
    ],
    stack: ['Next.js 16', 'React 19', 'Supabase', 'Tailwind 4', 'Maya Checkout', 'n8n', 'Capacitor'],
  },
  {
    company: 'Solid Lift Parts Inc.',
    where: 'United States · Remote',
    when: 'Oct 2023 – Oct 2024',
    role: 'Product Researcher',
    about: 'A US-based e-commerce company specializing in material handling and industrial lift equipment parts.',
    bullets: [
      'Conducted technical research on product specifications, competitor offerings and market positioning to support product development decisions.',
      'Built internal research tools and dashboards with Google Sheets scripting to streamline competitive analysis.',
      'Documented findings in structured reports, accelerating roadmap planning by 35%.',
    ],
    stack: ['Google Apps Script', 'Google Sheets', 'Data research'],
  },
  {
    company: 'Honda Cars Philippines, Inc.',
    where: 'Philippines · On-site',
    when: 'Mar 2016 – Sep 2017',
    role: 'Inventory Specialist',
    about: 'A leading automotive manufacturer and distributor operating across the Philippines.',
    bullets: [
      'Managed inventory tracking for automotive parts and accessories, keeping stock levels accurate and discrepancies low.',
      'Aligned inventory data with procurement and sales demand; reporting contributed to a 15% reduction in overstock and shortages.',
    ],
    stack: ['Inventory systems', 'Reporting'],
  },
]

export const education = {
  degree: 'Bachelor of Science in Computer Science',
  school: 'Laguna State Polytechnic University, Siniloan · Laguna, Philippines',
  when: 'Mar 2015 – Apr 2019',
}

export const stackGroups = [
  { name: 'Workflow orchestration', items: 'n8n (self-hosted / cloud), Make.com (iterators, aggregators, routers), Zapier (paths, looping, code steps)' },
  { name: 'CRM & sales automation', items: 'GoHighLevel (AI agents, workflow builder, smart lists, snapshots), Salesforce, Asana, Monday.com, Jira, ClickUp, Airtable' },
  { name: 'AI & LLM integration', items: 'Google Gemini API, OpenAI, VAPI voice AI, RAG architecture, persistent-memory agents' },
  { name: 'Full-stack development', items: 'React, Next.js, TypeScript, Tailwind, Node.js, Express, REST, GraphQL, Python (Flask / FastAPI), Supabase / Postgres' },
  { name: 'Security & protocols', items: 'OAuth 2.0 flows, JWT signing and exchange, API key management, webhooks, rate limiting' },
  { name: 'DevOps & tooling', items: 'Git, GitHub, Docker, Vercel, Render, Netlify, Postman, Figma' },
]

export const testimonialsNote = 'Client quotes available on request — every system above is live on the client’s own accounts.'

/* ── Under the hood: the real workflows (canvas screenshots; placeholders until the real captures land) ── */
export type Workflow = {
  slug: string
  category: string
  title: string
  client: string
  image: string
  metrics: { value: string; label: string }[]
  problem: string
  built: string
  /** how it runs, in order — written from the calling code, not the marketing */
  steps: string[]
  tools: string[]
  /** sample outputs (what the workflow actually produces): image + label */
  outputs?: { label: string; image: string; images?: string[] }[]
}

export const workflows: Workflow[] = [
  { slug: 'bed-angle-shots', category: 'AI Automation', title: 'Bed Product Shots Generator', client: 'Pan Furniture · Lucena City', image: '/workflows/bed-angle-shots.svg',
    metrics: [{ value: '7', label: 'generated angles' }, { value: '9', label: 'files in the ZIP' }, { value: '20 s', label: 'poll interval' }],
    problem: 'Every new bed model needed a studio session for the catalogue: front, side, corner, rear, with and without the mattress, plus the slat system in the chosen wood. Days of photography per SKU, and the wood tone never matched the swatch.',
    built: 'An n8n form takes one photo of the bed and one wood swatch. The workflow uploads both as reference images, builds seven locked prompts (same bed, same upholstery, four camera angles, mattress or visible slats), submits them to an image-edit model, polls until every job finishes, downloads the results and returns a gallery page that mirrors the two side views and hands back a ZIP of nine files. The same prompt set also runs from the IMS Website › Products tab, where results are copied into Supabase Storage because the model\'s result links expire.',
    steps: ['Form: upload the bed photo (slats visible) and the wood swatch.', 'Upload both files to the image host in parallel; keep the two download URLs.', 'Build Prompts: one shared description (design, colour lock, base pattern wrap) plus seven view blocks — front, right profile, corner, rear, and the three "wood" variants with continuous full-width slats copied from the swatch.', 'Create Task ×7 on the image-edit model; store each task id with its label.', 'Wait 20 s → Check Status for every task → Merge State; loop back until all are success or fail.', 'Extract Result → download each PNG → base64 → aggregate.', 'Show Gallery: an HTML page that renders the shots, mirrors right-profile and corner into left views, builds a ZIP in the browser and auto-downloads it.'],
    tools: ['n8n', 'Kie.ai', 'Nano Banana (image edit)', 'JavaScript'],
    outputs: [{ label: 'Generated shots', image: '/workflows/out/bed-angle-shots-gallery.png', images: ['/workflows/out/bedshots-web/01.jpg', '/workflows/out/bedshots-web/02.jpg', '/workflows/out/bedshots-web/03.jpg', '/workflows/out/bedshots-web/04.jpg', '/workflows/out/bedshots-web/05.jpg', '/workflows/out/bedshots-web/06.jpg', '/workflows/out/bedshots-web/07.jpg', '/workflows/out/bedshots-web/08.jpg', '/workflows/out/bedshots-web/09.jpg', '/workflows/out/bedshots-web/10.jpg', '/workflows/out/bedshots-web/11.jpg', '/workflows/out/bedshots-web/12.jpg', '/workflows/out/bedshots-web/13.jpg', '/workflows/out/bedshots-web/14.jpg', '/workflows/out/bedshots-web/15.jpg', '/workflows/out/bedshots-web/16.jpg', '/workflows/out/bedshots-web/17.jpg', '/workflows/out/bedshots-web/18.jpg', '/workflows/out/bedshots-web/19.jpg', '/workflows/out/bedshots-web/20.jpg', '/workflows/out/bedshots-web/21.jpg', '/workflows/out/bedshots-web/22.jpg', '/workflows/out/bedshots-web/23.jpg', '/workflows/out/bedshots-web/24.jpg', '/workflows/out/bedshots-web/25.jpg', '/workflows/out/bedshots-web/26.jpg', '/workflows/out/bedshots-web/27.jpg', '/workflows/out/bedshots-web/28.jpg', '/workflows/out/bedshots-web/29.jpg', '/workflows/out/bedshots-web/30.jpg', '/workflows/out/bedshots-web/31.jpg', '/workflows/out/bedshots-web/32.jpg', '/workflows/out/bedshots-web/33.jpg', '/workflows/out/bedshots-web/34.jpg', '/workflows/out/bedshots-web/35.jpg', '/workflows/out/bedshots-web/36.jpg', '/workflows/out/bedshots-web/37.jpg', '/workflows/out/bedshots-web/38.jpg', '/workflows/out/bedshots-web/39.jpg', '/workflows/out/bedshots-web/40.jpg'] }] },
  { slug: 'messenger-sales-agent', category: 'AI Agent', title: 'Messenger Sales Agent', client: 'Pan Furniture · Lucena City', image: '/workflows/messenger-sales-agent.svg',
    metrics: [{ value: '6 s', label: 'message debounce' }, { value: '2 h', label: 'human hand-off pause' }, { value: '1–2 s', label: 'typing delay' }],
    problem: 'Page messages about prices, stock, delivery and warranty arrived at all hours and piled up on two sales staff. Customers who typed three messages in a row got three separate answers, and a bot that kept talking after a staff member had already stepped in would embarrass the shop.',
    built: 'Meta delivers every page event to the IMS webhook, which forwards the full body to n8n and waits for its immediate EVENT_RECEIVED so Meta always gets a 200. n8n classifies the event, stores the inbound message and conversation, debounces for 6 seconds so a burst becomes one reply, and stays silent if a human replied in the last two hours. The reply comes from the script library the sales team edits in the IMS Website › Facebook Agent tab: whole-word keyword matching scored by hits, phrase length and position, priorities, alternate phrasings, a fallback, and the customer\'s first name. Mark-seen and a typing indicator sized to the reply length make it feel human; the outbound message is logged next to the inbound one.',
    steps: ['IMS /api/fb/webhook receives the Meta event and POSTs the whole body to n8n (8 s timeout, awaited so Vercel does not kill it).', 'Ack 200 → Parse Message: an echo from another app id means a staff member replied → Route → Mark Human (pause). Own echoes, stickers and receipts are dropped.', 'Store Inbound → Update Conversation (last message, last time).', 'Wait Debounce 6 s → Get Latest: if a newer message exists, this run stops; the newest run answers.', 'Get Conversation → Gate: skip if last_human_at is within 2 hours.', 'Get Scripts (active, by priority) → Get Profile (first name) → Match Script: scored whole-word matching, weak single-word hits on long messages fall to the fallback.', 'Mark Seen → Typing On → Wait Typing → FB Send Reply → Store Outbound with the matched script id.'],
    tools: ['n8n', 'Facebook Graph API', 'Supabase', 'JavaScript'],
    outputs: [{ label: 'Messenger conversation', image: '/workflows/out/messenger-sales-agent-chat.png' }, { label: 'Script library in the IMS', image: '/workflows/out/messenger-sales-agent-scripts.png' }] },
  { slug: 'sign-in-otp-email', category: 'Auth', title: 'Sign-in Verification Code Email', client: 'Pan Furniture · Lucena City', image: '/workflows/sign-in-otp-email.svg',
    metrics: [{ value: '5 min', label: 'code expiry' }, { value: '5 / 10 min', label: 'send and attempt cap' }, { value: '4', label: 'nodes' }],
    problem: 'The operations platform needed a second factor for staff sign-in without an SMS gateway or a transactional-email subscription, and it had to fail safe: if email were down, staff should still be able to work.',
    built: 'After the password check, the login action generates a 6-digit code, invalidates older unused codes, stores it with a 5-minute expiry and posts the address, code and TTL to this webhook. n8n renders the branded HTML (logo, code block, expiry note) and sends it through the company Gmail, returning the message id. Verification and rate limits stay in the app; OTP is only enforced when the webhook is configured, so the app is never bricked before setup.',
    steps: ['Login action: rate limit 5 sends per 10 minutes per email; mark previous unused codes used; insert the new code with expires_at = now + 5 min.', 'POST { email, code, ttl_minutes } to the n8n webhook with a 15 s timeout.', 'Build Email: Georgia-serif card, logo, 40 px spaced code, "expires in 5 minutes".', 'Gmail sends from the company account with reply-to set to the store; Respond returns { success, messageId }.', 'Verify step: 5 wrong attempts per 10 minutes behave like a wrong code — no hint that a limit exists.'],
    tools: ['n8n', 'Gmail', 'JavaScript'],
    outputs: [{ label: 'OTP email', image: '/workflows/out/sign-in-otp-email-otp.png' }] },
  { slug: 'daily-delivery-reminders', category: 'Scheduled Ops', title: 'Daily Delivery Reminders', client: 'Pan Furniture · Lucena City', image: '/workflows/daily-delivery-reminders.svg',
    metrics: [{ value: '06:00', label: 'Manila, daily' }, { value: '2 days', label: 'before delivery' }, { value: '3', label: 'follow-ups max' }],
    problem: 'Customers with a booked delivery were phoned one by one, and the ones who never confirmed their date were only noticed when the truck was already loading.',
    built: 'n8n owns the clock: a 6 AM Manila schedule calls one authenticated endpoint on the platform. The endpoint runs two sweeps in one call — follow-ups to customers who have not answered the initial confirmation (one per day, capped at three, then a CALL flag and a push to operations) and reminders to everyone whose delivery is two days out, with Confirm and Reschedule buttons. The logic and templates live in the app; the schedule is visible and adjustable in n8n without a deploy.',
    steps: ['Schedule Trigger fires at 06:00 Asia/Manila.', 'HTTP POST /api/delivery/reminders?key=… — rejected with 401 unless the key matches DELIVERY_CRON_KEY.', 'Sweep 1, follow-ups: orders still Awaiting Confirm get a resend once a day; after the third, the order is flagged CALL and operations gets a push notification.', 'Sweep 2, reminders: deliveries dated exactly two days ahead get the reminder email with Confirm — I\'ll be there and Reschedule.', 'Every email goes through the outbox (type, status, error) so the Email Log page can show and resend it.'],
    tools: ['n8n', 'Next.js API route', 'Supabase'],
    outputs: [{ label: 'Email the customer receives', image: '/workflows/out/daily-delivery-reminders-email.png' }] },
  { slug: 'order-confirmed-bir-invoice', category: 'Customer Emails', title: 'Order Confirmed — BIR Service Invoice', client: 'Pan Furniture · Lucena City', image: '/workflows/order-confirmed-bir-invoice.svg',
    metrics: [{ value: '30%', label: 'downpayment trigger' }, { value: '2 pages', label: 'receipt + BIR AR' }, { value: '1', label: 'send per payment id' }],
    problem: 'The moment a customer\'s 30% downpayment landed, they expected proof: the official BIR acknowledgement receipt for the whole order and the balance still due, without anyone in the office exporting a PDF.',
    built: 'When the downpayment is detected — a Maya payment online or cash and terminal collected in-store — the app renders a two-page PDF (page 1 Receipt of Payment for this payment, page 2 the BIR Acknowledgement Receipt for the full order), notes the remaining balance in the email and posts everything as base64 to this webhook. n8n rebuilds the attachment and sends it from the company Gmail.',
    steps: ['Downpayment detected: Maya webhook, or the in-store collect action (cash / terminal).', 'sendAckEmail: render Receipt of Payment + BIR AR, compute balance, build the Shopee-style HTML with item cards.', 'lib/email/send: outbox row (to, type, html), idempotency key so a double tap never sends twice, one retry on timeout.', 'POST { to, subject, html, filename, pdf_base64 } → Webhook → Build PDF Attachment → Gmail with the PDF attached.'],
    tools: ['n8n', 'Gmail', 'PDF', 'Supabase'],
    outputs: [{ label: 'Email the customer receives', image: '/workflows/out/order-confirmed-bir-invoice-email.png' }] },
  { slug: 'receipt-email-pdf', category: 'Customer Emails', title: 'Payment Receipt Email (PDF)', client: 'Pan Furniture · Lucena City', image: '/workflows/receipt-email-pdf.svg',
    metrics: [{ value: 'Every', label: 'payment, any method' }, { value: '2', label: 'PDFs attached' }, { value: 'receipt:<order>:<payment>', label: 'idempotency key' }],
    problem: 'Every payment — downpayment, balance, Maya, cash, terminal — needed a receipt in the customer\'s inbox the same minute, in one format, with no risk of sending it twice.',
    built: 'Each recorded payment calls sendReceiptEmail: the app reads the payment ledger, renders the Receipt of Payment plus a BIR-style Acknowledgement Receipt, tags each item as delivered, on this delivery or next delivery for partial deliveries, and posts the email and PDFs to this webhook. The sender keys every attempt on the payment id, so retries and double clicks are skipped; failures are visible in the Email Log and can be resent from there.',
    steps: ['Payment recorded (Maya or in-store) → sendReceiptEmail(order, payment).', 'Ledger read → Receipt of Payment PDF (this payment, payment terms) + BIR AR PDF as pdf2.', 'Subject "Payment received — ORD…", preheader with amount and method; item cards with partial-delivery tags.', 'lib/email/send: idempotency key receipt:<orderId>:<paymentId>; outbox log; POST to Webhook → Build PDF Attachment → Send Receipt (PDF).'],
    tools: ['n8n', 'Gmail', 'PDF', 'Supabase'],
    outputs: [{ label: 'Email the customer receives', image: '/workflows/out/receipt-email-pdf-email.png' }] },
  { slug: 'acknowledgement-receipt-72mm', category: 'Customer Emails', title: 'Acknowledgement Receipt (72 mm)', client: 'Pan Furniture · Lucena City', image: '/workflows/acknowledgement-receipt-72mm.svg',
    metrics: [{ value: '72 mm', label: 'thermal slip' }, { value: 'RMA', label: 'rework / repair path' }, { value: '3', label: 'nodes' }],
    problem: 'Rework and repair jobs (RMA) collect a downpayment in-store and print a 72 mm slip; the customer needed the same slip in email so the record survived the paper and matched what the cashier printed.',
    built: 'The rework email path has three kinds — QR payment request, rework receipt, and this acknowledgement. For "ack", the app renders the 72 mm slip as PDF, finds the item photo from the RMA row or the catalogue, attaches an SVG copy to the order\'s transaction images, and posts to the dedicated ACK webhook (falling back to the receipt hook). n8n attaches the PDF and sends it.',
    steps: ['Rework downpayment collected in-store → sendReworkEmail(kind = "ack").', 'Render the 72 mm Acknowledgement slip PDF (customer, RMA no., parts, charges, collected amount, method).', 'Item photo lookup: returns.item_image → product by SKU → product by name.', 'Subject "Acknowledgement Receipt — Pan Furniture RMA-…"; POST → Webhook → Build PDF Attachment → Send Acknowledgement Receipt.'],
    tools: ['n8n', 'Gmail', 'PDF'],
    outputs: [{ label: 'Email the customer receives', image: '/workflows/out/acknowledgement-receipt-72mm-email.png' }] },
  { slug: 'warranty-certificate-pdf', category: 'Customer Emails', title: 'Warranty Certificate (PDF)', client: 'Pan Furniture · Lucena City', image: '/workflows/warranty-certificate-pdf.svg',
    metrics: [{ value: 'Signed', label: 'installation form' }, { value: '5', label: 'progress-rail steps' }, { value: '3', label: 'nodes' }],
    problem: 'Warranty documents were handed over on delivery and lost by the time a claim came in; the installer\'s signed form stayed on the tablet.',
    built: 'At installation sign-off the tablet captures the signed warranty form. The app converts that image into a PDF certificate and posts it with a completion email (progress rail Confirmed → Packed → Out for Delivery → Arrived → Installation, all done) to this webhook. n8n attaches the PDF and sends it, so the customer and the store both hold a dated copy.',
    steps: ['Installer marks the job complete and signs the warranty form on the tablet.', 'sendWarrantyEmail: warrantyPdfFromImage(signed form URL) → PDF; order email and number looked up.', 'Email body: "Installation complete · certificate attached as PDF" with Gmail order schema markup.', 'POST → Webhook → Build PDF Attachment → Send Warranty (PDF).'],
    tools: ['n8n', 'Gmail', 'PDF'],
    outputs: [{ label: 'Email the customer receives', image: '/workflows/out/warranty-certificate-pdf-email.png' }] },
  { slug: 'for-payment-email-qr', category: 'Customer Emails', title: 'For-Payment Email (inline QR)', client: 'Pan Furniture · Lucena City', image: '/workflows/for-payment-email-qr.svg',
    metrics: [{ value: '30%', label: 'downpayment QR' }, { value: 'Auto', label: 'scan detection' }, { value: '2', label: 'nodes' }],
    problem: 'Balance requests went out as chat messages with a screenshot of a QR code — easy to miss, impossible to audit, and the cashier still had to match the payment by hand.',
    built: 'forPaymentEmailCore computes the amount due (30% downpayment, or a custom amount after items are added), creates a Maya QR Ph payment for it and stores the checkout id on the order so the later scan is recognised automatically. The QR PNG is uploaded to storage and embedded as a hosted image, because CID inline images are unreliable in the Gmail node. The email goes to this webhook and out through the company Gmail.',
    steps: ['createOrder or the guarded "Send for-payment email" action → forPaymentEmailCore(orderId).', 'Amount due = 30% of total (or the custom amount), capped at the balance; stop if nothing is due.', 'Maya createQrPayment → save maya_checkout_id / maya_ref on the order (PENDING_TOKEN).', 'Render QR PNG → upload to Supabase Storage → email with <img src=hosted URL> and the amount.', 'POST { to, subject, html } → Webhook → Send For-Payment Email.'],
    tools: ['n8n', 'Gmail', 'Maya QR Ph', 'Supabase Storage'],
    outputs: [{ label: 'Email the customer receives', image: '/workflows/out/for-payment-email-qr-email.png' }] },
  { slug: 'out-for-delivery-tracking', category: 'Customer Emails', title: 'Out-for-Delivery Tracking Email', client: 'Pan Furniture · Lucena City', image: '/workflows/out-for-delivery-tracking.svg',
    metrics: [{ value: 'Track', label: 'tokenised link' }, { value: 'Live', label: 'driver map' }, { value: '2', label: 'nodes' }],
    problem: '"Where is my order?" calls started the moment a truck left the warehouse.',
    built: 'When the driver taps Out for Delivery on the tablet, the app builds a tracking email whose button opens the website\'s Track Order page with a signed token (falling back to the internal live map with the destination pin when the store URL is not configured), lists what is on the truck — only the repaired item for a rework trip — and posts it to this webhook for immediate sending.',
    steps: ['Driver tablet → Out for Delivery → sendOutForDeliveryEmail(order, pin).', 'Track URL: <store>/track?order=…&t=<token>, else /track-preview.html?order&dlat&dlng&pin.', 'Subject "Your order is on the way — ORD…"; items on this trip (rework = repaired item only).', 'POST → Webhook → Send Tracking Email.'],
    tools: ['n8n', 'Gmail', 'Live GPS'],
    outputs: [{ label: 'Email the customer receives', image: '/workflows/out/out-for-delivery-tracking-email.png' }] },
  { slug: 'delivery-arrived-email', category: 'Customer Emails', title: 'Delivery Arrived Email', client: 'Pan Furniture · Lucena City', image: '/workflows/delivery-arrived-email.svg',
    metrics: [{ value: 'Arrived', label: 'tablet event' }, { value: 'Parcel', label: 'Gmail tracking markup' }, { value: '2', label: 'nodes' }],
    problem: 'Customers who were not at the door needed a nudge the moment the team arrived — not a phone call from the driver while the truck idled.',
    built: 'The Arrived tap on the delivery tablet hits /api/delivery/arrive, which renders full item cards with photos and per-item partial-delivery tags, adds Gmail parcel-tracking schema so the inbox shows the delivery status, and posts the email to this webhook. n8n sends it within seconds of the truck stopping.',
    steps: ['Tablet → Arrived → POST /api/delivery/arrive (rate-limited).', 'Build item cards from receipt_items (rework = repaired item only) + DELIVERED / THIS DELIVERY / NEXT DELIVERY tags.', 'Gmail parcel schema: OrderInTransit, expected arrival today; preheader "Installation & setup starts now".', 'POST → Webhook → Send Arrived Email.'],
    tools: ['n8n', 'Gmail'],
    outputs: [{ label: 'Email the customer receives', image: '/workflows/out/delivery-arrived-email-email.png' }] },
  { slug: 'delivery-confirmation-email', category: 'Customer Emails', title: 'Delivery Confirmation Email', client: 'Pan Furniture · Lucena City', image: '/workflows/delivery-confirmation-email.svg',
    metrics: [{ value: 'Group', label: 'sent per route group' }, { value: 'Confirm', label: 'one-tap button' }, { value: '2', label: 'nodes' }],
    problem: 'Delivery dates agreed on the phone were forgotten or disputed, and operations could not tell who had actually confirmed.',
    built: 'When operations sets a date and team for a group in the Delivery Queue, sendGroupConfirmations emails every order in the group at once: date, team, COD amount and a single Confirm Delivery Date button that lands on a tokenised confirm page. Redelivery after rework uses the same shape with different wording. Orders left Awaiting Confirm are picked up by the daily follow-up sweep. The email goes through the outbox with an idempotency key and out via this webhook.',
    steps: ['Delivery Queue → set date + team + coordinator for a group → sendGroupConfirmations.', 'Per order: subject with order number and date; Confirm Delivery Date → /delivery-confirm/<dq_token>; "Need a different date? Reply or message us".', 'Order marked Awaiting Confirm (dq_sent_at); unanswered ones get the 6 AM follow-ups.', 'POST → Webhook → Send Email (Gmail).'],
    tools: ['n8n', 'Gmail', 'Supabase'],
    outputs: [{ label: 'Email the customer receives', image: '/workflows/out/delivery-confirmation-email-email.png' }] },
  { slug: 'telegram-job-search-bot', category: 'Internal Tool', title: 'Telegram Job Search Bot', client: 'Internal tool · job search', image: '/workflows/telegram-job-search-bot.svg',
    metrics: [{ value: '2', label: 'job APIs queried in parallel' }, { value: '1', label: 'message replaces a morning of checking' }, { value: '0', label: 'listings shown twice' }],
    problem: 'Checking several remote job boards by hand every morning is slow, and the same listings come back day after day with no way to mark one as seen.',
    built: 'A self-hosted n8n workflow triggered by a Telegram message. It reads the request in plain language ("gohighlevel last 3 days"), queries two job APIs in parallel, merges and de-duplicates the results, scores each one against the skills asked for, drops anything older than the requested window, and stores everything in PostgreSQL so saved and hidden jobs persist between searches. Every database query is parameterised rather than string-built, so scraped job titles and user input can never alter the SQL.',
    steps: ['Telegram Trigger receives a message or a button callback; Normalize Update flattens both into one shape.', 'Is Callback? — button taps go to Save? / Hide? / Alert?: the job is written to PostgreSQL and the bot replies Saved / Hidden / Alert set.', 'Is /saved? — the /saved command reads the saved list from PostgreSQL, formats it and sends it back.', 'Otherwise Parse Search turns the plain-language request into keywords and a day window, then calls Remotive and Remote OK in parallel.', 'Merge Sources → Normalize Sources → Rank Jobs: de-duplicate, score against the requested skills, drop anything outside the window.', 'Store Jobs → Get Hidden: persist the batch and remove anything the user hid before → Format Results → Send Results to Telegram.'],
    tools: ['n8n', 'PostgreSQL', 'Docker', 'Telegram API', 'JavaScript'],
    outputs: [] },
  { slug: 'faceless-ai-videos', category: 'AI Content', title: 'Automated Faceless AI Videos', client: 'Content creator · personal brand', image: '/workflows/faceless-ai-videos.svg',
    metrics: [{ value: '8+', label: 'platforms published per run' }, { value: '3', label: 'stages: script, render, publish' }, { value: '0', label: 'manual steps' }],
    problem: 'Scripting, producing, and posting short-form video to every platform by hand eats hours a day and rarely stays consistent.',
    built: 'An AI agent writes the script, a faceless video renders, and Blotato publishes it to 8+ platforms on a schedule. A full idea-to-post video pipeline runs unattended — consistent daily output with zero manual steps.',
    steps: ['Schedule Trigger → AI Agent brainstorms an idea and returns a structured script.', 'Prepare Video → Create Video (render API) → Wait → Get Video when the render is ready.', 'Prepare for Publish → Upload to Blotato.', 'Fan-out: Instagram, YouTube, Facebook, Threads, LinkedIn, Twitter, TikTok, Bluesky via Blotato; an image variant goes to Pinterest.'],
    tools: ['n8n', 'OpenAI', 'Blotato'],
    outputs: [] },
  { slug: 'ai-sales-agent', category: 'AI Agent', title: 'AI Sales Agent', client: 'Sales · outreach team', image: '/workflows/ai-sales-agent.svg',
    metrics: [{ value: '3', label: 'touches per lead, with memory' }, { value: 'Sheets', label: 'source of truth, status written back' }, { value: '0', label: 'dropped follow-ups' }],
    problem: 'Reps forget follow-ups and warm leads go cold before the 2nd or 3rd touch.',
    built: 'Loads leads from Sheets and runs AI 1st/2nd/3rd-touch email sequences with memory, writing each status back to the sheet. Every lead gets a consistent, personalized multi-touch follow-up — no dropped follow-ups, no manual tracking.',
    steps: ['Schedule → Load Leads from Google Sheets → Filter the ones due today.', 'Switch on touch number: three Gemini agents write the 1st, 2nd or 3rd email with the thread so far as memory.', 'Gmail sends; the lead row is updated with the touch and timestamp.', 'A Gmail trigger watches for replies and marks the lead replied so the sequence stops.'],
    tools: ['n8n', 'Google Gemini', 'Google Sheets', 'Gmail'],
    outputs: [] },
  { slug: 'ai-customer-support', category: 'AI Support', title: 'AI Customer Support Automation', client: 'Support inbox owner', image: '/workflows/ai-customer-support.svg',
    metrics: [{ value: 'Instant', label: 'reply on routine tickets' }, { value: '2', label: 'classes: support or other' }, { value: '0', label: 'human review on routine mail' }],
    problem: 'Repetitive support emails pile up and drag response times down.',
    built: 'Gmail trigger → Gemini classifies the email → an AI agent drafts a context-aware reply → auto-sends and labels it. Routine tickets are answered instantly with no human review; the team only touches genuine edge cases.',
    steps: ['Gmail Trigger on every new message.', 'Text Classifier (Gemini) sorts it: Customer Support or Other. Other → No Operation.', 'AI Agent (Gemini + a Code tool) drafts the reply with the email context.', 'Reply to the message → Add label so the thread is marked handled.'],
    tools: ['n8n', 'Google Gemini', 'Gmail'],
    outputs: [] },
  { slug: 'rag-pipeline-chatbot', category: 'RAG', title: 'RAG Pipeline & AI Chatbot', client: 'Knowledge-heavy team', image: '/workflows/rag-pipeline-chatbot.svg',
    metrics: [{ value: 'Auto', label: 're-index on every Drive upload' }, { value: 'Pinecone', label: 'vector store' }, { value: 'Sourced', label: 'answers from your own files' }],
    problem: 'Answers are buried across scattered documents nobody has time to search.',
    built: 'A Drive upload triggers ingestion → OpenAI embeddings land in Pinecone → a chat agent answers from that knowledge base. Instant, sourced answers — and the knowledge base re-indexes itself every time a file is dropped in.',
    steps: ['Google Drive Trigger fires on file created → Download file.', 'Pinecone Vector Store ingests it: Default Data Loader splits the document, OpenAI embeds the chunks.', 'Chat trigger → AI Agent with the OpenAI chat model.', 'The agent uses Pinecone as a retrieval tool (same embeddings) and answers from the indexed documents.'],
    tools: ['n8n', 'OpenAI', 'Pinecone', 'Google Drive'],
    outputs: [] },
  { slug: 'ai-agent-endpoint', category: 'AI Agent', title: 'AI Agent', client: 'Reusable building block', image: '/workflows/ai-agent-endpoint.svg',
    metrics: [{ value: 'Webhook', label: 'any app can call it' }, { value: 'Memory', label: 'conversation kept per session' }, { value: 'Reused', label: 'core of multiple client builds' }],
    problem: 'Apps need a flexible AI endpoint that can reason and call tools — not a rigid, single-purpose script.',
    built: 'A webhook-triggered agent with Gemini, conversation memory, and HTTP tool calls that fetches context and responds. A drop-in AI brain any app can hit via webhook — reused as the core of multiple client builds.',
    steps: ['Webhook: GET → If → Respond (health check); POST carries the request.', 'Get a document pulls the context the agent should know.', 'AI Agent (Gemini chat model + Simple Memory) reasons over the request and the context.', 'HTTP Request delivers the answer to the calling app.'],
    tools: ['n8n', 'Google Gemini'],
    outputs: [] },
  { slug: 'weather-social-post', category: 'AI Content', title: 'Social Media Post Weather Forecast', client: 'Local brand · social account', image: '/workflows/weather-social-post.svg',
    metrics: [{ value: 'Daily', label: 'one post every morning' }, { value: 'Live', label: 'weather in every card' }, { value: '0', label: 'repeated quotes or images' }],
    problem: 'Producing a fresh, on-brand social post every single day is tedious and easy to skip.',
    built: 'A morning schedule builds a quote + live-weather card via Gemini, dedupes against Sheets, and posts to Facebook. A unique, timely post goes out every morning with zero effort.',
    steps: ['Schedule Trigger → Generate Quote (Gemini agent) — checks the Sheet so no quote repeats, saves the new one.', 'OpenWeatherMap fetches the current weather.', 'AI Agent composes the card: picks a background image (deduped via Sheets), returns structured output.', 'HTTP Request renders the image → Facebook Graph API publishes the post.'],
    tools: ['n8n', 'Google Gemini', 'OpenWeatherMap', 'Facebook'],
    outputs: [] },
  { slug: 'asmr-content-pipeline', category: 'AI Content', title: 'ASMR Content Pipeline', client: 'Faceless content channel', image: '/workflows/asmr-content-pipeline.svg',
    metrics: [{ value: 'Polls', label: 'until the render is ready' }, { value: 'JWT', label: 'service-account auth, no keys in nodes' }, { value: 'File', label: 'finished clip delivered' }],
    problem: 'AI video generation is slow and needs babysitting while renders finish.',
    built: 'Gemini writes the prompts, Google\'s AI video API renders, the flow polls until ready, then converts to a file. Hands-off content generation that waits on its own renders and delivers finished clips.',
    steps: ['Schedule → Generate Prompt: Gemini returns a structured video prompt.', 'Secret Payload → JWT → exchange for an access token.', 'Generate Video → Wait → Get Generated Video; is Done? loops back to Wait until the render finishes.', 'is Filtered? / is Error? guard the result → Convert to File (base64 → binary).'],
    tools: ['n8n', 'Google Gemini', 'Google Veo'],
    outputs: [] },
  { slug: 'invoice-follow-up', category: 'Finance Ops', title: 'Invoice Follow-Up System', client: 'Freelancer · agency finance', image: '/workflows/invoice-follow-up.svg',
    metrics: [{ value: '09:00', label: 'daily check' }, { value: '3', label: 'escalation tiers' }, { value: '30+', label: 'days triggers an internal alert' }],
    problem: 'Chasing overdue invoices manually is awkward, inconsistent, and easy to forget.',
    built: 'Daily read from Sheets, tier invoices by days overdue, send escalating Gmail reminders, and alert internally at 30+ days. Overdue invoices chase themselves — nothing slips past 30 days unnoticed.',
    steps: ['Daily Check at 9 AM → Read Invoices from Google Sheets.', 'Code node filters overdue rows and calculates days overdue.', 'Route by Overdue Tier: first reminder, second reminder, or escalation.', 'Gmail sends the tiered email; at 30+ days the freelancer is alerted too; the sheet row is updated with the level.'],
    tools: ['n8n', 'Google Sheets', 'Gmail'],
    outputs: [] },
  { slug: 'lead-temperature-router', category: 'Lead Ops', title: 'Lead Temperature Router', client: 'Lead-gen operations', image: '/workflows/lead-temperature-router.svg',
    metrics: [{ value: '3', label: 'tiers: Cold, Warm, Hot' }, { value: 'Instant', label: 'routing on submit' }, { value: 'Sheets', label: 'one row per lead' }],
    problem: 'New leads need routing by intent, but manual triage is slow and inconsistent.',
    built: 'A form submission is scored Cold / Warm / Hot via a Switch and appended to the matching Google Sheet. Every lead is triaged and routed the instant it arrives.',
    steps: ['On form submission → Switch scores the answers.', 'Cold / Warm / Hot set the tier and tags.', 'Google Sheets Append writes the lead to the matching sheet.'],
    tools: ['n8n', 'Google Sheets'],
    outputs: [] },
  { slug: 'ai-lead-scraper-qualifier', category: 'Lead Gen', title: 'AI Lead Scraper & Qualifier', client: 'B2B lead generation', image: '/workflows/ai-lead-scraper-qualifier.svg',
    metrics: [{ value: 'Apify', label: 'raw dataset in' }, { value: 'ZeroBounce', label: 'every email validated' }, { value: 'Claude', label: 'scores each lead' }],
    problem: 'Building a clean, qualified list means hours of scraping, deduping, email hunting, and manual scoring.',
    built: 'Apify dataset → clean & dedupe → scrape site + subpages for emails → ZeroBounce validation → Claude scores each lead → qualified rows to Sheets. A raw scrape becomes a validated, AI-scored lead list with zero manual touch.',
    steps: ['Get dataset items from Apify → Normalize → Clean and Dedupe.', 'Has Website? → fetch the HTML, extract an email, scan subpages; no website skips the fetch. Merge both paths.', 'Limiter → ZeroBounce validates each email → a Wait buffers the AI rate limit.', 'Claude qualifies each lead → Parse Qualifier Output → Build Final Row → Append to Google Sheet.'],
    tools: ['n8n', 'Apify', 'ZeroBounce', 'Claude', 'Google Sheets'],
    outputs: [] },
  { slug: 'erp-replica-console-sync', category: 'Data Pipeline', title: 'ERP Replica → Console Sync', client: 'E-commerce importer · purchasing console', image: '/workflows/erp-replica-console-sync.svg',
    metrics: [{ value: '7', label: 'feeds on the same 4-node pattern' }, { value: '15 min', label: 'fastest cadence (channel sales)' }, { value: '1', label: 'JSON payload per load' }],
    problem: 'The purchasing console needed order lines, purchase orders, refunds, returns, channel sales, container rows and in-stock history from the ERP every day, without buyers touching spreadsheets.',
    built: 'One four-node pattern, cloned per feed: a schedule fires, a read-only query hits the ERP replica, a Code node packs the rows into one JSON payload, and a single parameterised INSERT loads the console table. Each feed has its own window so the replica is never hammered at once.',
    steps: ['1:30 AM order tracker (all lines by year) · 2:00 AM refunds & adjustments · 2:30 AM returns log (full history).', '4:00 AM purchase orders (all lines) · 4:30 AM in-stock rate (12 months by year).', 'Every 15 min channel sales (marketplace / storefront / other) · every 30 min container rows (one per PO + SKU, with a batch guard).', 'Replica query → Pack payload → Load: the console reads the loaded table directly; nothing is edited by hand.'],
    tools: ['n8n', 'SQL Server replica', 'PostgreSQL'],
    outputs: [] },
  { slug: 'sku-health-spines', category: 'Data Pipeline', title: 'SKU Health Spines', client: 'E-commerce importer · purchasing console', image: '/workflows/sku-health-spines.svg',
    metrics: [{ value: '4', label: 'spines: rates, in-stock, velocity, monthly sales' }, { value: '05:30–06:30', label: 'staggered morning runs' }, { value: '2', label: 'SQL passes after each load' }],
    problem: 'Forecasting needs per-SKU rates, in-stock %, unshipped velocity and an 11-month sales summary that all line up on one SKU spine, refreshed before buyers start work.',
    built: 'Each spine has the same shape: ERP query → batch/normalise columns in Code → load its forecast table → two SQL passes that attach the rows to the shared forecast_data spine and rebuild the views the console reads.',
    steps: ['5:30 AM in-stock percentage · 6:00 AM rates · 6:30 AM unshipped velocity · every 15 min monthly sales (kit BOM).', 'Code node normalises columns / batches all SKUs into one statement.', 'Load the forecast_* table, then SQL pass 1 joins to the spine and pass 2 rebuilds dependent views.'],
    tools: ['n8n', 'SQL Server replica', 'PostgreSQL'],
    outputs: [] },
  { slug: 'storefront-stock-status-match', category: 'Data Pipeline', title: 'Storefront Stock Status Match', client: 'E-commerce importer · purchasing console', image: '/workflows/storefront-stock-status-match.svg',
    metrics: [{ value: '08:00', label: 'daily' }, { value: 'Kits', label: 'components resolved from the ERP' }, { value: 'SKU', label: 'matched to storefront listings' }],
    problem: 'The storefront lists kits and variants under its own SKUs; the ERP knows components. Nobody could say which storefront listing was actually in stock.',
    built: 'Extract kit components from the ERP, load them, pull the storefront catalogue through its API, match every listing to forecast rows by SKU and write the matches — the Storefront Stock monitor reads that table.',
    steps: ['ERP kit components extract → Build load SQL → Load storefront_status.', 'Generate an API token → Fetch storefront SKUs.', 'Read forecast rows → Match SKUs (kit + variant rules) → Write matches.'],
    tools: ['n8n', 'SQL Server replica', 'PostgreSQL', 'Shopify API'],
    outputs: [] },
  { slug: 'channel-margin-sync', category: 'Data Pipeline', title: 'Channel Margin Sync', client: 'E-commerce importer · purchasing console', image: '/workflows/channel-margin-sync.svg',
    metrics: [{ value: 'Hourly', label: 'summary cards + per-SKU rows' }, { value: 'CM1–CM3', label: 'per channel, carrier cost fixed' }, { value: '2', label: 'loads per run' }],
    problem: 'Channel margin numbers were recomputed in spreadsheets with an inconsistent carrier cost, so the cards and the per-SKU table never agreed.',
    built: 'One hourly run pulls the summary-card aggregates and the per-SKU margin rows from the ERP replica with the carrier cost fixed in the query, packs each and loads both tables the Channel Margin Console reads.',
    steps: ['Hourly → Replica summary cards → Pack → Load sales_summary.', 'Replica per-SKU (landed cost, fees, marketing spend) → Pack → Load sales_analytics.', 'The console computes CM1 / CM2 / CM3 from these two tables only.'],
    tools: ['n8n', 'SQL Server replica', 'PostgreSQL'],
    outputs: [] },
  { slug: 'airtable-tracker-mirrors', category: 'Data Pipeline', title: 'Airtable Tracker Mirrors', client: 'E-commerce importer · purchasing console', image: '/workflows/airtable-tracker-mirrors.svg',
    metrics: [{ value: '3', label: 'trackers: PO, invoice, shipping request' }, { value: 'Hourly', label: 'upsert by row hash' }, { value: '10', label: 'attachments per batch' }],
    problem: 'Buyers kept PO, invoice and shipping-request trackers in Airtable; the console needed the same rows and their attachments in Postgres, kept in sync without double entry.',
    built: 'Every hour each tracker is read in pages, mapped and hashed so only changed rows are upserted, removed rows deleted, and linked-record names resolved. Attachments are pruned, downloaded from Airtable in batches of ten, uploaded to storage, and their URLs saved next to the row.',
    steps: ['Every Hour → Airtable search (PO tracker; invoice and shipping-request trackers run the same graph).', 'Loop Over Items (1000) → Map + Hash → Build Query → Upsert; a delete query removes rows no longer in Airtable; Resolve Linked Names fills related names.', 'Prune Attachment Files → Get Copied Attachments → Prepare downloads → Batch Files (10 at a time).', 'Download from Airtable → Upload to Storage → Build Storage URLs → Save Attachment Links, then next batch.'],
    tools: ['n8n', 'Airtable', 'PostgreSQL', 'Supabase Storage'],
    outputs: [] },
  { slug: 'demand-planner-email-scheduler', category: 'Reporting', title: 'Demand Planner Email Scheduler', client: 'E-commerce importer · purchasing console', image: '/workflows/demand-planner-email-scheduler.svg',
    metrics: [{ value: '1 min', label: 'schedule check' }, { value: 'Per vendor', label: 'one email per recipient' }, { value: 'DB', label: 'schedule and recipients live in the console' }],
    problem: 'Vendor owners wanted the reorder list in their inbox on their own schedule, and the schedule had to be editable in the console, not in n8n.',
    built: 'A one-minute tick reads the schedule table; when a run is due it loads the recipients and their Order Now items, builds one email per recipient, sends through Gmail and stamps the schedule so it never double-sends.',
    steps: ['Every 1 Minute → Check Schedule Due (Postgres) → Is Schedule Due? (false → Not Due Yet).', 'Get Recipients → Get Order Now Items scoped to each recipient\'s vendors.', 'Build Email Per Recipient → Send Gmail → Update Schedule with the sent timestamp.'],
    tools: ['n8n', 'PostgreSQL', 'Gmail'],
    outputs: [] },
  { slug: 'inventory-report-email-sender', category: 'Reporting', title: 'Storefront Stock Report Sender', client: 'E-commerce importer · purchasing console', image: '/workflows/inventory-report-email-sender.svg',
    metrics: [{ value: 'POST', label: 'from the console\'s Send button' }, { value: '4', label: 'nodes' }, { value: 'Gmail', label: 'delivery' }],
    problem: 'The Storefront Stock monitor needed a “send this report now” button that mails the filtered view to the assigned vendor emails.',
    built: 'The console posts the rendered report and recipients to a webhook; a Code node shapes the message, Gmail sends it, and the response goes back so the UI can confirm.',
    steps: ['Console button → POST webhook with recipients + HTML.', 'Code in JavaScript builds subject/body per factory summary.', 'Gmail sends → Respond to Webhook returns the message id.'],
    tools: ['n8n', 'Gmail'],
    outputs: [] },
  { slug: 'storefront-revenue-backfill', category: 'Analytics', title: 'Storefront Revenue Backfill', client: 'E-commerce importer · purchasing console', image: '/workflows/storefront-revenue-backfill.svg',
    metrics: [{ value: '365', label: 'days per run' }, { value: '1', label: 'API call per day, looped' }, { value: 'Range', label: 'rebuilt after the loop' }],
    problem: 'Ad Spend vs Revenue needed a year of daily storefront revenue to blend against ad spend, and the storefront API only answers per day.',
    built: 'Generate 365 dates, loop: fetch that day\'s orders, total them, save the daily row; when the loop is done, one SQL rebuilds the revenue range the analytics page reads.',
    steps: ['Generate Token → Generate 365 Dates → Loop Over Items.', 'Per day: Get Orders → Calculate Daily Totals → Save Daily Revenue → back to the loop.', 'Done branch → Revenue Range (Postgres) rebuilds the contiguous series.'],
    tools: ['n8n', 'Shopify API', 'Supabase', 'PostgreSQL'],
    outputs: [] },
  { slug: 'storefront-categories-graphql', category: 'Analytics', title: 'Storefront Product Categories (GraphQL)', client: 'E-commerce importer · purchasing console', image: '/workflows/storefront-categories-graphql.svg',
    metrics: [{ value: '08:00', label: 'daily' }, { value: 'Paged', label: 'GraphQL cursor with rate-limit wait' }, { value: 'Per day', label: 'category totals saved' }],
    problem: 'Category-level sales per day are not available from the storefront reports; they have to be built from every order, page by page, within the API rate limit.',
    built: 'For each date: initialise page state, query orders through GraphQL, accumulate, and if more pages remain wait for the rate limit and continue; then process product categories and save the day\'s totals.',
    steps: ['Daily 8 AM → Generate Token → Generate Dates → Loop.', 'Init Page State → Storefront GraphQL → Accumulate Orders → More Pages? (true → Wait → query again).', 'Process: Product Categories → Save Categories → next date.'],
    tools: ['n8n', 'Shopify GraphQL', 'Supabase'],
    outputs: [] },
  { slug: 'shopifyql-analytics-pulls', category: 'Analytics', title: 'ShopifyQL Analytics Pulls', client: 'E-commerce importer · purchasing console', image: '/workflows/shopifyql-analytics-pulls.svg',
    metrics: [{ value: '2', label: 'pulls: session attribution, product categories' }, { value: 'Daily', label: '8 AM and 9 AM' }, { value: 'Top 5', label: 'channels view rebuilt' }],
    problem: 'Session attribution by channel and category sales were only visible inside the storefront admin; the Ad Spend and channel pages needed them as tables.',
    built: 'A dated loop runs a ShopifyQL query per day, processes the rows, skips empty days and saves to Supabase; when the loop finishes, Postgres rebuilds the date ranges and the top-5 channels view.',
    steps: ['Generate Token → Generate Dates → Loop.', 'ShopifyQL Query → Process rows → Skip Empty? → Save → next date.', 'Done → Rebuild Session/Category Ranges → Top-5 channels view.'],
    tools: ['n8n', 'ShopifyQL', 'Supabase', 'PostgreSQL'],
    outputs: [] },
]
